name: yard

on:
  push:

jobs:
  delight:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        disservice: ["renew", "ditch", "somebody", "outlet", "mission"]
        whereas: ["mission", "overload", "lightning", "exist"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java --enable-native-access=ALL-UNNAMED -jar wz.jar
